using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace FitTracker.Services;

public interface IAnalyticsPdfExportService
{
    byte[] ExportDashboardPdf(AdvancedAnalyticsSummary summary);
}

public class AnalyticsPdfExportService : IAnalyticsPdfExportService
{
    static AnalyticsPdfExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] ExportDashboardPdf(AdvancedAnalyticsSummary summary)
    {
        return Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Margin(32);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(text => text.FontSize(10));

                page.Header().Column(column =>
                {
                    column.Item().Text("FitTracker Analytics Dashboard")
                        .FontSize(20)
                        .Bold()
                        .FontColor(Colors.Blue.Darken2);
                    column.Item().Text($"Range: {summary.RangeStart:MMM dd, yyyy} - {summary.RangeEnd:MMM dd, yyyy}")
                        .FontColor(Colors.Grey.Darken2);
                });

                page.Content().Column(column =>
                {
                    column.Spacing(18);

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Element(container => ComposeMetricCard(container, "Completed workouts", summary.TotalWorkouts.ToString()));
                        row.RelativeItem().Element(container => ComposeMetricCard(container, "Average duration", $"{summary.AverageWorkoutDuration:0.0} min"));
                        row.RelativeItem().Element(container => ComposeMetricCard(container, "Average volume", summary.AverageVolumePerWorkout.ToString("N0")));
                        row.RelativeItem().Element(container => ComposeMetricCard(container, "PRs", summary.TotalPersonalRecords.ToString()));
                    });

                    column.Item().Element(container => ComposeListSection(
                        container,
                        "Most worked muscle groups",
                        summary.MostWorkedMuscleGroups.Select(item => $"{item.MuscleGroup}: {item.Volume:N0} volume across {item.WorkoutCount} workouts")));

                    column.Item().Element(container => ComposeListSection(
                        container,
                        "Least worked muscle groups",
                        summary.LeastWorkedMuscleGroups.Select(item => $"{item.MuscleGroup}: {item.Volume:N0} volume across {item.WorkoutCount} workouts")));

                    column.Item().Element(container => ComposeListSection(
                        container,
                        "Weekly volume trend",
                        summary.VolumeTrend.Select(point => $"{point.Label}: {point.Volume:N0} volume, {point.WorkoutCount} workout(s), {point.AverageDuration:0.0} min avg")));

                    column.Item().Element(container => ComposeListSection(
                        container,
                        "PR timeline",
                        summary.PersonalRecordTimeline.Select(point => $"{point.Label}: {point.RecordCount} PR(s), best 1RM {point.BestOneRepMax:0.##}")));

                    column.Item().Element(container => ComposeListSection(
                        container,
                        "Recent personal records",
                        summary.RecentPersonalRecords.Any()
                            ? summary.RecentPersonalRecords.Select(record => $"{record.Date:MMM dd, yyyy} - {record.Exercise.Name}: {record.Weight:0.##} x {record.Reps} (1RM {record.OneRepMax:0.##})")
                            : ["No personal records in the current range."]));
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by FitTracker · ");
                    text.Span(DateTime.UtcNow.ToString("MMM dd, yyyy HH:mm 'UTC'"));
                });
            });
        }).GeneratePdf();
    }

    private static void ComposeMetricCard(IContainer container, string label, string value)
    {
        container
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Background(Colors.Grey.Lighten5)
            .Padding(12)
            .Column(column =>
            {
                column.Item().Text(label)
                    .FontSize(9)
                    .FontColor(Colors.Grey.Darken2);
                column.Item().PaddingTop(4).Text(value)
                    .FontSize(15)
                    .Bold();
            });
    }

    private static void ComposeListSection(IContainer container, string title, IEnumerable<string> items)
    {
        container.Column(column =>
        {
            column.Item().Text(title)
                .FontSize(13)
                .Bold()
                .FontColor(Colors.Blue.Darken2);

            foreach (var item in items)
            {
                column.Item()
                    .PaddingTop(4)
                    .Row(row =>
                    {
                        row.ConstantItem(10).Text("•");
                        row.RelativeItem().Text(item);
                    });
            }
        });
    }
}
